### ISSUE TITLE
html entities

### ISSUE THREAD

**Issue by franfranfranfran** [jondtipton/colmar-academy#2]
https://github.com/jondtipton/colmar-academy/blob/master/index.html#L166
etc...

consider using an html entity to represent the & special character to ensure that the character displays correctly across all browsers. more info can be found [here](https://www.w3schools.com/html/html_entities.asp)

**Comment by jondtipton** [comment]
not sure I followed this - i used &copy for the copyright symbol - I thought that was the html entity?
